#!/bin/sh
git subtree pull --prefix=bitbake https://git.openembedded.org/bitbake.git 2.0 --squash
git subtree pull --prefix=meta-artesyn https://github.com/voltumna-linux/meta-artesyn.git master --squash
git subtree pull --prefix=meta-intel https://git.yoctoproject.org/meta-intel kirkstone --squash
git subtree pull --prefix=meta-mingw https://git.yoctoproject.org/meta-mingw kirkstone --squash
git subtree pull --prefix=meta-openembedded https://git.openembedded.org/meta-openembedded kirkstone --squash
git subtree pull --prefix=meta-ti https://git.yoctoproject.org/meta-ti kirkstone --squash
git subtree pull --prefix=meta-tango https://github.com/voltumna-linux/meta-tango.git master --squash
git subtree pull --prefix=openembedded-core https://git.openembedded.org/openembedded-core kirkstone --squash
git subtree pull --prefix=meta-dpdk https://git.yoctoproject.org/meta-dpdk kirkstone --squash
git subtree pull --prefix=meta-arm https://git.yoctoproject.org/meta-arm kirkstone --squash
git subtree pull --prefix=meta-intel-fpga https://git.yoctoproject.org/meta-intel-fpga kirkstone --squash
git subtree pull --prefix=meta-clang https://github.com/kraj/meta-clang.git kirkstone --squash
git subtree pull --prefix=meta-amd https://git.yoctoproject.org/meta-amd kirkstone --squash
git subtree pull --prefix=meta-intel-qat https://git.yoctoproject.org/meta-intel-qat master --squash
