#!/bin/sh
git subtree pull --prefix=bitbake https://git.openembedded.org/bitbake.git 1.46 --squash
git subtree pull --prefix=meta-artesyn https://github.com/voltumna-linux/meta-artesyn.git dunfell --squash
git subtree pull --prefix=meta-intel https://git.yoctoproject.org/meta-intel dunfell --squash
git subtree pull --prefix=meta-mingw https://git.yoctoproject.org/meta-mingw dunfell --squash
git subtree pull --prefix=meta-openembedded https://git.openembedded.org/meta-openembedded dunfell --squash
git subtree pull --prefix=meta-ti https://git.yoctoproject.org/meta-ti dunfell --squash
git subtree pull --prefix=meta-tango https://github.com/voltumna-linux/meta-tango.git dunfell --squash
git subtree pull --prefix=openembedded-core https://git.openembedded.org/openembedded-core dunfell --squash
git subtree pull --prefix=meta-dpdk https://git.yoctoproject.org/meta-dpdk dunfell --squash
git subtree pull --prefix=meta-arm https://git.yoctoproject.org/meta-arm dunfell --squash
git subtree pull --prefix=meta-altera https://github.com/kraj/meta-altera.git dunfell --squash
git subtree pull --prefix=meta-clang https://github.com/kraj/meta-clang.git dunfell --squash
git subtree pull --prefix=meta-intel-qat https://git.yoctoproject.org/meta-intel-qat dunfell --squash



