#@TYPE: Machine
#@NAME: Dinet machine
#@DESCRIPTION: Machine configuration for the Dinet board 

DEFAULTTUNE = "cortexa9hf-neon"
require include/cyclone5.conf
MACHINEOVERRIDES =. "cyclone5:"

UBOOT_CONFIG[dinet] = "socfpga_dinet_defconfig"
UBOOT_CONFIG = "dinet"
UBOOT_EXTLINUX = "0"
KERNEL_DEVICETREE:append = "\
			socfpga_cyclone5_dinet.dtb \
			"

PRIMARY_NETIF = "eth0"
ROOT = "root=/dev/mmcblk0p3"
ROOTUSB = "root=/dev/sda3"
WKS_FILE = "sdimage-cyclone5-arria5.wks"

IMAGE_FSTYPES = "tar wic wic.bmap"

IMAGE_BOOT_FILES:remove = "extlinux.conf;extlinux/extlinux.conf"
IMAGE_BOOT_FILES:append = "boot.scr.uimg uEnv.txt"

MACHINE_EXTRA_RRECOMMENDS:append = " kernel-modules mtd-utils"

MACHINE_FEATURES:remove = "qemu-usermode"
OPENBLAS_TARGET = "CORTEXA9"
