#@TYPE: Machine
#@NAME: KVM virtual machine
#@DESCRIPTION: Machine configuration for the http://linux-kvm.org virtual machine 

require include/intel-common.inc
require include/tune-nehalem.inc

IMAGE_FSTYPES = "tar wic.qcow2"

PRIMARY_NETIF = "enp0s3"
ROOT = "root=/dev/vda2"

EXTRA_IMAGEDEPENDS += "grub-efi"
PREFERRED_PROVIDER_virtual/bootloader = "grub-efi"

MACHINE_EXTRA_RRECOMMENDS:remove = "kernel-modules linux-firmware"
MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-efivars kernel-module-parport \
	kernel-module-parport-pc kernel-module-ata-piix kernel-module-uio \
	kernel-module-iwlwifi kernel-module-cfg80211 kernel-module-i915 \
	kernel-module-video"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "thermald"

OPENBLAS_TARGET = "NEHALEM"

COMPATIBLE_MACHINE:pn-dpdk = "kvm-nehalem"
COMPATIBLE_MACHINE:pn-dpdk-module = "kvm-nehalem"
