#@TYPE: Machine
#@NAME: KVM virtual machine
#@DESCRIPTION: Machine configuration for the http://linux-kvm.org virtual machine 

require include/naples.inc

MACHINEOVERRIDES =. "kvm:"

IMAGE_FSTYPES = "wic"

PRIMARY_NETIF = "enp0s2f0"
ROOT = "root=/dev/vda2"

EXTRA_IMAGEDEPENDS += "grub-efi grub-bootconf"

PREFERRED_PROVIDER_virtual/bootloader = "grub-efi"

MACHINE_EXTRA_RRECOMMENDS:remove = "kernel-modules linux-firmware"
MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-efivars kernel-module-parport \
	kernel-module-parport-pc kernel-module-ata-piix kernel-module-uio \
	kernel-module-iwlwifi kernel-module-cfg80211 kernel-module-i915 \
	kernel-module-video"

COMPATIBLE_MACHINE:pn-nativesdk-dpdk = "(.*)"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "thermald"

OPENBLAS_TARGET = "ZEN"
