#!/bin/sh

set -e

DISK=/dev/mmcblk1
DIR=/usr/share/u-boot-ti-staging-mmc1

sfdisk -q ${DISK} <<-__EOF__
,32MiB,0xC,*
__EOF__

sync

mkfs.vfat -F 16 ${DISK}p1 -S 512 -h 0 -n boot

MOUNTDIR=$(mktemp -d)

mount -t vfat ${DISK}p1 ${MOUNTDIR}
cp ${DIR}/MLO ${DIR}/u-boot.img ${MOUNTDIR}
umount ${MOUNTDIR}
rmdir ${MOUNTDIR}

