DISTRO = "voltumna"
DISTRO_NAME ??= "Voltumna"
DISTRO_CODENAME = "Age of Machine"
DISTRO_VERSION = "2.5${IMAGE_VERSION}"
SDK_VENDOR = "-voltumnasdk"

MAINTAINER = "Alessio Igor Bogani <alessio.bogani@elettra.eu>"

TARGET_VENDOR = "-voltumna"

DISTRO_FEATURES = "acl xattr largefile keyboard ldconfig pci pam systemd \
	stateless-rootfs usbgadget usbhost wifi usrmerge opengl polkit \
	api-documentation"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

# Use reasonable kernel, image and sdk filenames
KERNEL_ARTIFACT_NAME = "${MACHINE}-${PKGE}-${PKGV}-${PKGR}"
KERNEL_IMAGEDEST = "usr/boot"

IMAGE_NAME_SUFFIX = ""
IMAGE_VERSION_SUFFIX = ""
IMAGE_NAME = "${IMAGE_BASENAME}-${MACHINE}-${DISTRO_VERSION}"

SDK_NAME_PREFIX = "${IMAGE_BASENAME}"
SDK_VERSION = "${DISTRO_VERSION}"
SDK_NAME = "${SDK_NAME_PREFIX}-${SDKMACHINE}-${MACHINE}"
SDKPATHINSTALL = "/opt/${SDK_NAME_PREFIX}/${SDK_VERSION}"
TOOLCHAIN_OUTPUTNAME = "${SDK_NAME}-${SDK_VERSION}"
SDK_PS1 = "${DISTRO_NAME} ${MACHINE} ${SDK_VERSION}:\$ "

# Use systemd
INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

# Avoid busybox
VIRTUAL-RUNTIME_base-utils = ""
VIRTUAL-RUNTIME_base-utils-hwclock = ""
VIRTUAL-RUNTIME_base-utils-syslog = ""
VIRTUAL-RUNTIME_login_manager = ""

# Disable creation of the tarball of modules
MODULE_TARBALL_DEPLOY = "0"

# Relay on systemd for volatile implementation
VOLATILE_LOG_DIR = "no"
FILESYSTEM_PERMS_TABLES = "files/fs-perms-voltumna.txt"

# We trying to use the same kernel and booloader release among all our boards
OLDEST_KERNEL = "5.10"
LINUXLIBCVERSION = "5.10"
PREFERRED_VERSION_virtual/kernel ?= "5.10%"
PREFERRED_VERSION_linux-intel = "${PREFERRED_VERSION_virtual/kernel}"
PREFERRED_VERSION_linux-intel-rt = "${PREFERRED_VERSION_virtual/kernel}"
PREFERRED_VERSION_linux-yocto = "${PREFERRED_VERSION_virtual/kernel}"
PREFERRED_VERSION_linux-yocto-rt = "${PREFERRED_VERSION_virtual/kernel}"
PREFERRED_VERSION_linux-bb.org = "${PREFERRED_VERSION_virtual/kernel}"
PREFERRED_VERSION_linux-socfpga-lts = "${PREFERRED_VERSION_virtual/kernel}"

PREFERRED_VERSION_nativesdk-libgfortran = "${GCCVERSION}"

PREFERRED_VERSION_cpptango = "9.3%"
PREFERRED_VERSION_nativesdk-cpptango = "9.3%"
PREFERRED_VERSION_python3-pytango = "9.3%"
PREFERRED_VERSION_nativesdk-python3-pytango = "9.3%"
PREFERRED_VERSION_nativesdk-pogo = "9.7%"

# Use an initramfs
INITRAMFS_IMAGE_BUNDLE = "1"
INITRAMFS_IMAGE = "voltumna-initramfs"

# Set few defaults
ROOT_HOME = "/root"
LOCALE_UTF8_ONLY = "1"

# For the bios recipe
HOSTTOOLS += "pdftotext"

# Set http server's root
WWWDIR = "${datadir}/www/localhost/html"

# We support only one libc (glibc)
TCLIBCAPPEND = ""

SANITY_TESTED_DISTROS = " \
	ubuntu-18.04\n \
	ubuntu-20.04\n"

# Notify users when the format of TMPDIR changes in an incompatible way
OELAYOUT_ABI = "12"

# Avoid use of static libs
require conf/distro/include/no-static-libs.inc
# Leverage Yocto uninative tarball
require conf/distro/include/yocto-uninative.inc
INHERIT += "uninative"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"
BB_HASHSERVE ??= "auto"
