#ifndef __MAL_CHECKS_H__
#define __MAL_CHECKS_H__ 1

#define HAVE_LINUX_COMPILE_H 1
#define HAVE_ASM_RMAP_H 1

#define HAVE_PTE_KUNMAP 1
#define HAVE_PTE_OFFSET_NESTED 1
#define HAVE_IO_REMAP_PFN_RANGE 1
#define HAVE_PTE_OFFSET_MAP_NESTED 1
#define HAVE_IT_MAPSIZE 1

#define HAVE_REMAP_PFN_RANGE 1
#define HAVE_REMAP_PAGE_RANGE 1
#define HAVE_REMAP_PAGE_RANGE_5ARGS 1
//#define HAVE_MMAP_UP_WRITE 1
#define HAVE_DO_MUNMAP_4ARGS 1
#define HAVE_CLASS_SIMPLE 1
#define HAVE_KTHREAD_RUN 1

//#define HAVE_SKB_LINEARIZE_2ARGS 1
#define HAVE_SKB_TRANSPORT_OFFSET 1
#define HAVE_RCU_TASKLIST_LOCK 1
#define HAVE_CURRENT_EUID 1
#define HAVE_NEW_NAPI 1
#define HAVE_NAPI_GRO_FRAGS 1
#define HAVE_SKB_FILL_PAGE_DESC 1
#define HAVE_HW_VLAN_CTAG_RX 1
#define HAVE_SKB_FRAG_MAP 1
//#define HAVE_OLD_PAGE_COUNT 1

#define HAVE_DST_GET_NEIGHBOUR_NOREF 1
//#define HAVE_DST_GET_NEIGHBOUR 1
//#define HAVE_DST_IN_UNION 1
//#define HAVE_DST_STRAIGHT 1

#endif /* __MAL_CHECKS_H__ */
