# SPDX-FileCopyrightText: Copyright (C) 2025 Bruce Ashfield
#
# SPDX-License-Identifier: MIT
#
# vcontainer-tarball.bb
# ===========================================================================
# Standalone SDK-style tarball for vdkr/vpdmn container tools
# ===========================================================================
#
# This recipe uses Yocto's populate_sdk infrastructure to create a
# relocatable standalone distribution of vdkr (Docker) and vpdmn (Podman).
#
# USAGE:
#   MACHINE=qemux86-64 bitbake vcontainer-tarball
#   MACHINE=qemuarm64 bitbake vcontainer-tarball
#
# OUTPUT:
#   tmp/deploy/sdk/vcontainer-standalone-<arch>.tar.xz
#   tmp/deploy/sdk/vcontainer-standalone-<arch>.sh (self-extracting installer)
#
# ===========================================================================

SUMMARY = "Standalone SDK tarball for vdkr and vpdmn container tools"
DESCRIPTION = "A relocatable standalone distribution of vdkr (Docker) and \
               vpdmn (Podman) CLI tools using Yocto SDK infrastructure."
HOMEPAGE = "https://git.yoctoproject.org/meta-virtualization/"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

# file:// SRC_URI entries land directly in UNPACKDIR, not a subdirectory
S = "${UNPACKDIR}"

# Use our custom SDK installer template with vcontainer-specific messages
FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
TOOLCHAIN_SHAR_EXT_TMPL = "${THISDIR}/files/toolchain-shar-extract.sh"

# Declare script sources so BitBake tracks changes and rebuilds when they change
SRC_URI = "\
    file://vrunner.sh \
    file://vrunner-backend-qemu.sh \
    file://vrunner-backend-xen.sh \
    file://vcontainer-common.sh \
    file://vdkr.sh \
    file://vpdmn.sh \
    file://boot-xen.sh \
    file://vxn.sh \
    file://vrunner-backend-qemu-xen.sh \
    file://toolchain-shar-extract.sh \
"

# No target sysroot - host tools only (like buildtools-tarball)
TOOLCHAIN_TARGET_TASK = ""
TARGET_ARCH = "none"
TARGET_OS = "none"

# Must use ${SDK_ARCH}-${SDKPKGSUFFIX} (e.g. x86_64-nativesdk) to match
# the pattern explicitly listed in SSTATE_ARCHS, which SPDX's find_jsonld()
# searches when locating the static recipe SPDX document generated by
# do_create_recipe_spdx.  Using ${SDK_ARCH}_${SDK_OS} (x86_64_linux) is NOT
# in SSTATE_ARCHS and causes do_create_spdx to fatal with "Could not find a
# static SPDX document named static-vcontainer-tarball".
# See: meta/classes-global/sstate.bbclass SSTATE_ARCHS definition and
#      buildtools-tarball.bb for the reference pattern.

# Host tools to include via SDK
# Note: nativesdk-qemu-vcontainer is a minimal QEMU without OpenGL/virgl
# to avoid mesa -> llvm -> clang build dependency chain
TOOLCHAIN_HOST_TASK = "\
    nativesdk-sdk-provides-dummy \
    nativesdk-qemu-vcontainer \
    nativesdk-socat \
    nativesdk-expect \
    "

# SDK naming and metadata
TOOLCHAIN_OUTPUTNAME = "vcontainer-standalone"
SDK_TITLE = "vcontainer tools (vdkr/vpdmn)"

# SDK configuration (same pattern as buildtools-tarball)
MULTIMACH_TARGET_SYS = "${SDK_ARCH}-nativesdk${SDK_VENDOR}-${SDK_OS}"
PACKAGE_ARCH = "${SDK_ARCH}-${SDKPKGSUFFIX}"
PACKAGE_ARCHS = ""
SDK_PACKAGE_ARCHS += "vcontainer-dummy-${SDKPKGSUFFIX}"

RDEPENDS = "${TOOLCHAIN_HOST_TASK}"
EXCLUDE_FROM_WORLD = "1"

inherit populate_sdk
inherit toolchain-scripts-base
inherit nopackages
inherit container-registry

# Must be set AFTER inherit populate_sdk (class sets it to target arch)
REAL_MULTIMACH_TARGET_SYS = "none"

# Disable tasks we don't need
deltask install
deltask populate_sysroot

# No config site needed
TOOLCHAIN_NEED_CONFIGSITE_CACHE = ""
INHIBIT_DEFAULT_DEPS = "1"

do_populate_sdk[stamp-extra-info] = "${PACKAGE_ARCH}"

# ===========================================================================
# Architecture mapping
# ===========================================================================
VCONTAINER_TARGET_ARCH = "${@d.getVar('MACHINE').replace('qemuarm64', 'aarch64').replace('qemux86-64', 'x86_64')}"
VCONTAINER_KERNEL_NAME = "${@'Image' if d.getVar('MACHINE') == 'qemuarm64' else 'bzImage'}"
VCONTAINER_MC = "${@'vruntime-aarch64' if d.getVar('MACHINE') == 'qemuarm64' else 'vruntime-x86-64'}"

# ===========================================================================
# Multiconfig dependencies for blobs
# ===========================================================================
# By default, builds BOTH x86_64 and aarch64 via mcdepends.
# To limit to a single architecture, set in local.conf:
#   VCONTAINER_ARCHITECTURES = "x86_64"           # x86_64 only
#   VCONTAINER_ARCHITECTURES = "aarch64"          # aarch64 only
#
# Helper function (optional - for auto-detection if needed)
def get_available_architectures(d):
    import os
    topdir = d.getVar('TOPDIR')
    available = []
    arch_info = {
        'x86_64': ('vruntime-x86-64', 'qemux86-64'),
        'aarch64': ('vruntime-aarch64', 'qemuarm64'),
    }
    for arch, (mc, machine) in arch_info.items():
        deploy_dir = os.path.join(topdir, 'tmp-%s' % mc, 'deploy', 'images', machine, 'vdkr', arch)
        if os.path.isdir(deploy_dir):
            available.append(arch)
    # If nothing available yet, default to current MACHINE's arch (will be built)
    if not available:
        available.append(d.getVar('VCONTAINER_TARGET_ARCH'))
    return " ".join(sorted(available))

# Default to both architectures. Override in local.conf if you only want one:
#   VCONTAINER_ARCHITECTURES = "x86_64"
#   VCONTAINER_ARCHITECTURES = "aarch64"
VCONTAINER_ARCHITECTURES ?= "x86_64 aarch64"

# vxn (Xen dom0 image) is opt-in -- it is more niche than vdkr/vpdmn, so it is
# NOT packaged into the tarball unless explicitly enabled. To include it:
#   VCONTAINER_INCLUDE_VXN = "1"
# and add the vxn-<arch> multiconfig to BBMULTICONFIG (currently x86_64 only;
# aarch64 Xen boots via a different mechanism and is a follow-up).
VCONTAINER_INCLUDE_VXN ?= "0"

# vdkr (docker) and vpdmn (podman) are included by default. Set either to "0" to
# build a subset SDK -- e.g. a vxn-only SDK for AXIS:
#   VCONTAINER_INCLUDE_VXN = "1"
#   VCONTAINER_INCLUDE_VDKR = "0"
#   VCONTAINER_INCLUDE_VPDMN = "0"
# Their blobs (~127MB each per arch) are then neither built nor bundled.
VCONTAINER_INCLUDE_VDKR ?= "1"
VCONTAINER_INCLUDE_VPDMN ?= "1"

# Conditionally set mcdepends based on available multiconfigs
# (avoids parse errors when BBMULTICONFIG is not set, e.g. yocto-check-layer)
#
# Two layers of dependency per arch:
#
#   1. initramfs-create:do_deploy
#      Task ordering — guarantees the rootfs.img / kernel / initramfs are
#      staged under tmp-<mc>/deploy/images/<machine>/<tool>/<arch>/ before
#      do_populate_sdk reads them.
#
#   2. rootfs-image:do_image_complete
#      Defence-in-depth for sstate consistency. Without this, a rootfs
#      content change (e.g. adding netavark, switching iptables -> nftables)
#      would only invalidate the tarball's sstate hash if it propagates
#      cleanly through rootfs-image:do_build -> initramfs-create:do_compile
#      -> initramfs-create:do_deploy -> mcdepends. Any break in that chain
#      (the DEPLOY_DIR-input sstate pattern is one known way to get a stale
#      hit) re-introduces the netavark-stale-tarball failure mode. Listing
#      the rootfs-image task directly puts its hash in our chain regardless
#      of intermediate propagation, and costs nothing if the chain was
#      already healthy.
python () {
    bbmulticonfig = (d.getVar('BBMULTICONFIG') or "").split()
    mcdeps = []
    inc_vdkr = d.getVar('VCONTAINER_INCLUDE_VDKR') == '1'
    inc_vpdmn = d.getVar('VCONTAINER_INCLUDE_VPDMN') == '1'
    for mc in ['vruntime-x86-64', 'vruntime-aarch64']:
        if mc in bbmulticonfig:
            if inc_vdkr:
                mcdeps.append('mc::%s:vdkr-initramfs-create:do_deploy' % mc)
                mcdeps.append('mc::%s:vdkr-rootfs-image:do_image_complete' % mc)
            if inc_vpdmn:
                mcdeps.append('mc::%s:vpdmn-initramfs-create:do_deploy' % mc)
                mcdeps.append('mc::%s:vpdmn-rootfs-image:do_image_complete' % mc)

    # vxn (opt-in): depend on the Xen dom0 image built in the vxn-<arch> MC.
    # Guarded by VCONTAINER_INCLUDE_VXN and MC presence so the tarball never
    # pulls in the vxn image (or errors on a missing MC) when vxn is off.
    if d.getVar('VCONTAINER_INCLUDE_VXN') == '1':
        for mc in ['vxn-x86-64', 'vxn-aarch64']:
            if mc in bbmulticonfig:
                mcdeps.append('mc::%s:xen-image-minimal:do_image_complete' % mc)

    if mcdeps:
        d.setVarFlag('do_populate_sdk', 'mcdepends', ' '.join(mcdeps))

    # Build-time banner is in do_populate_sdk:append() below
}

# ===========================================================================
# Custom SDK files - environment script AND blobs/scripts
# ===========================================================================
# IMPORTANT: All custom files must be added in create_sdk_files:append()
# because SDK_POSTPROCESS_COMMAND runs archive_sdk BEFORE any appended commands.
# The order is: create_sdk_files -> check_sdk_sysroots -> archive_sdk -> ...
# ===========================================================================
create_sdk_files:append () {
    # Variables - these are Yocto variables expanded at parse time
    TOPDIR="${TOPDIR}"
    THISDIR="${THISDIR}"
    ARCHITECTURES="${VCONTAINER_ARCHITECTURES}"
    CONTAINER_REGISTRY_SECURE="${CONTAINER_REGISTRY_SECURE}"
    CONTAINER_REGISTRY_CA_CERT="${CONTAINER_REGISTRY_CA_CERT}"

    # SDK output directory
    SDK_OUT="${SDK_OUTPUT}/${SDKPATH}"

    bbnote "TOPDIR=${TOPDIR}"
    bbnote "THISDIR=${THISDIR}"
    bbnote "ARCHITECTURES=${ARCHITECTURES}"
    bbnote "SDK_OUT=${SDK_OUT}"

    # -----------------------------------------------------------------------
    # Step 1: Copy blobs and scripts (MUST happen before archive_sdk)
    # -----------------------------------------------------------------------
    VDKR_INCLUDED=0
    VPDMN_INCLUDED=0

    # Copy blobs for each architecture
    for ARCH in ${ARCHITECTURES}; do
        bbnote "Adding vcontainer blobs for ${ARCH}"

        # Determine multiconfig and kernel name for this arch
        case "${ARCH}" in
            aarch64)
                MC="vruntime-aarch64"
                MC_MACHINE="qemuarm64"
                KERNEL="Image"
                ;;
            x86_64)
                MC="vruntime-x86-64"
                MC_MACHINE="qemux86-64"
                KERNEL="bzImage"
                ;;
            *)
                bbwarn "Unknown architecture: ${ARCH}"
                continue
                ;;
        esac

        MC_DEPLOY="${TOPDIR}/tmp-${MC}/deploy/images/${MC_MACHINE}"
        bbnote "MC_DEPLOY=${MC_DEPLOY} for ${ARCH}"

        # Copy vdkr blobs (skip entirely when VCONTAINER_INCLUDE_VDKR = 0)
        if [ "${VCONTAINER_INCLUDE_VDKR}" = "1" ]; then
            mkdir -p "${SDK_OUT}/vdkr-blobs/${ARCH}"
            VDKR_SRC="${MC_DEPLOY}/vdkr/${ARCH}"
            if [ -d "${VDKR_SRC}" ]; then
                for blob in ${KERNEL} initramfs.cpio.gz rootfs.img; do
                    if [ -f "${VDKR_SRC}/${blob}" ]; then
                        cp "${VDKR_SRC}/${blob}" "${SDK_OUT}/vdkr-blobs/${ARCH}/"
                        bbnote "Copied vdkr blob: ${ARCH}/${blob}"
                    else
                        bbfatal "vdkr blob not found: ${VDKR_SRC}/${blob}"
                    fi
                done
                VDKR_INCLUDED=1
            else
                bbfatal "vdkr blobs not found for ${ARCH}. Build them first with:
  bitbake mc:${MC}:vdkr-initramfs-create"
            fi
        fi

        # Copy vpdmn blobs (skip entirely when VCONTAINER_INCLUDE_VPDMN = 0)
        if [ "${VCONTAINER_INCLUDE_VPDMN}" = "1" ]; then
            mkdir -p "${SDK_OUT}/vpdmn-blobs/${ARCH}"
            VPDMN_SRC="${MC_DEPLOY}/vpdmn/${ARCH}"
            if [ -d "${VPDMN_SRC}" ]; then
                for blob in ${KERNEL} initramfs.cpio.gz rootfs.img; do
                    if [ -f "${VPDMN_SRC}/${blob}" ]; then
                        cp "${VPDMN_SRC}/${blob}" "${SDK_OUT}/vpdmn-blobs/${ARCH}/"
                        bbnote "Copied vpdmn blob: ${ARCH}/${blob}"
                    else
                        bbfatal "vpdmn blob not found: ${VPDMN_SRC}/${blob}"
                    fi
                done
                VPDMN_INCLUDED=1
            else
                bbfatal "vpdmn blobs not found for ${ARCH}. Build them first with:
  bitbake mc:${MC}:vpdmn-initramfs-create"
            fi
        fi
    done

    # Copy scripts from layer
    FILES_DIR="${THISDIR}/files"

    # Copy shared scripts
    for script in vrunner.sh vrunner-backend-qemu.sh vrunner-backend-xen.sh vcontainer-common.sh; do
        if [ -f "${FILES_DIR}/${script}" ]; then
            cp "${FILES_DIR}/${script}" "${SDK_OUT}/"
            chmod 755 "${SDK_OUT}/${script}"
            bbnote "Copied ${script}"
        else
            bbfatal "${script} not found in ${FILES_DIR}"
        fi
    done

    # Copy and set up vdkr
    if [ "${VDKR_INCLUDED}" = "1" ] && [ -f "${FILES_DIR}/vdkr.sh" ]; then
        cp "${FILES_DIR}/vdkr.sh" "${SDK_OUT}/vdkr"
        chmod 755 "${SDK_OUT}/vdkr"
        # Create symlinks for each included architecture
        for ARCH in ${ARCHITECTURES}; do
            if [ -d "${SDK_OUT}/vdkr-blobs/${ARCH}" ]; then
                ln -sf vdkr "${SDK_OUT}/vdkr-${ARCH}"
                bbnote "Created symlink vdkr-${ARCH}"
            fi
        done
        bbnote "Installed vdkr"
    fi

    # Copy and set up vpdmn
    if [ "${VPDMN_INCLUDED}" = "1" ] && [ -f "${FILES_DIR}/vpdmn.sh" ]; then
        cp "${FILES_DIR}/vpdmn.sh" "${SDK_OUT}/vpdmn"
        chmod 755 "${SDK_OUT}/vpdmn"
        # Create symlinks for each included architecture
        for ARCH in ${ARCHITECTURES}; do
            if [ -d "${SDK_OUT}/vpdmn-blobs/${ARCH}" ]; then
                ln -sf vpdmn "${SDK_OUT}/vpdmn-${ARCH}"
                bbnote "Created symlink vpdmn-${ARCH}"
            fi
        done
        bbnote "Installed vpdmn"
    fi

    # -----------------------------------------------------------------------
    # vxn (opt-in): Xen dom0 image blob + boot-xen.sh launcher
    # -----------------------------------------------------------------------
    INCLUDE_VXN="${VCONTAINER_INCLUDE_VXN}"
    if [ "${INCLUDE_VXN}" = "1" ]; then
        VXN_INCLUDED=0
        for ARCH in ${ARCHITECTURES}; do
            case "${ARCH}" in
                x86_64) VXN_MC="vxn-x86-64"; VXN_MACHINE="qemux86-64" ;;
                *)
                    bbwarn "vxn: no multiconfig for ${ARCH} yet (x86_64 only); skipping"
                    continue
                    ;;
            esac
            VXN_WIC="${TOPDIR}/tmp-${VXN_MC}/deploy/images/${VXN_MACHINE}/xen-image-minimal-${VXN_MACHINE}.rootfs.wic"
            if [ -f "${VXN_WIC}" ]; then
                mkdir -p "${SDK_OUT}/vxn-blobs/${ARCH}"
                cp -L "${VXN_WIC}" "${SDK_OUT}/vxn-blobs/${ARCH}/xen-dom0.wic"
                VXN_INCLUDED=1
                bbnote "Copied vxn blob: ${ARCH}/xen-dom0.wic"
            else
                bbfatal "VCONTAINER_INCLUDE_VXN=1 but Xen image not found:
  ${VXN_WIC}
Build it first with:
  bitbake mc:${VXN_MC}:xen-image-minimal"
            fi
        done
        if [ "${VXN_INCLUDED}" = "1" ]; then
            # mode 1 (transparent host-side, the vdkr/vpdmn UX): the qemu-xen
            # backend boots the dom0 wic under QEMU and proxies commands into
            # dom0. Ships the backend + the vxn frontend with per-arch symlinks
            # (vxn-x86_64 -> vxn); arch is inferred from the invoked name, and
            # vxn.sh auto-selects qemu-xen when it finds a dom0 *.wic blob.
            if [ -f "${FILES_DIR}/vrunner-backend-qemu-xen.sh" ]; then
                cp "${FILES_DIR}/vrunner-backend-qemu-xen.sh" "${SDK_OUT}/"
                chmod 755 "${SDK_OUT}/vrunner-backend-qemu-xen.sh"
            else
                bbfatal "vrunner-backend-qemu-xen.sh not found in ${FILES_DIR}"
            fi
            if [ -f "${FILES_DIR}/vxn.sh" ]; then
                cp "${FILES_DIR}/vxn.sh" "${SDK_OUT}/vxn"
                chmod 755 "${SDK_OUT}/vxn"
                for ARCH in ${ARCHITECTURES}; do
                    if [ -d "${SDK_OUT}/vxn-blobs/${ARCH}" ]; then
                        ln -sf vxn "${SDK_OUT}/vxn-${ARCH}"
                        bbnote "Created symlink vxn-${ARCH}"
                    fi
                done
                bbnote "Installed vxn host CLI (qemu-xen backend)"
            else
                bbfatal "vxn.sh not found in ${FILES_DIR}"
            fi

            # vpm: drive dom0's container engine from the host over ssh, for the
            # two-context image load (docker save | vpm load) without the ssh
            # key/port/TMPDIR incantation. Engine via VXN_ENGINE (default docker,
            # matching the vexpose demo path). NOT for run -- run uses plain
            # docker/podman after `eval $(vxn vexpose env)`. (No 'vdk' alias --
            # too easily confused with the vdkr QEMU CLI.)
            if [ -f "${FILES_DIR}/vpm.sh" ]; then
                cp "${FILES_DIR}/vpm.sh" "${SDK_OUT}/vpm"
                chmod 755 "${SDK_OUT}/vpm"
                # Named engine entrypoints (same proxy, different dom0 engine),
                # for hosts that don't have the client installed:
                #   vdo  -> docker,  vpd -> podman,  vctr -> containerd
                # These proxy INTO dom0 (each container is a Xen DomU); distinct
                # from vdkr/vpdmn (the QEMU-VM CLIs). vpm stays the load helper.
                ln -sf vpm "${SDK_OUT}/vctr"
                ln -sf vpm "${SDK_OUT}/vpd"
                ln -sf vpm "${SDK_OUT}/vdo"
                bbnote "Installed vpm + vdo + vpd + vctr helpers"
            fi

            # mode 2 (interactive): boot-xen.sh drops you into the dom0 shell.
            if [ -f "${FILES_DIR}/boot-xen.sh" ]; then
                cp "${FILES_DIR}/boot-xen.sh" "${SDK_OUT}/boot-xen.sh"
                chmod 755 "${SDK_OUT}/boot-xen.sh"
                bbnote "Installed boot-xen.sh (vxn mode-2 launcher)"
            fi
        fi
    fi

    # Copy CA certificate for secure registry mode (if available)
    SECURE_MODE="${CONTAINER_REGISTRY_SECURE}"
    CA_CERT="${CONTAINER_REGISTRY_CA_CERT}"
    if [ "${SECURE_MODE}" = "1" ] && [ -f "${CA_CERT}" ]; then
        mkdir -p "${SDK_OUT}/registry"
        cp "${CA_CERT}" "${SDK_OUT}/registry/ca.crt"
        bbnote "Included secure registry CA certificate"
    elif [ "${SECURE_MODE}" = "1" ]; then
        bbwarn "Secure registry mode enabled but CA cert not found at ${CA_CERT}"
        bbwarn "Run: bitbake container-registry-index -c generate_registry_script"
    fi

    # CA-cert drop dir: users place their corporate root CA (PEM/.crt) here and
    # it is installed into the container VM's / dom0's system trust store at
    # boot, so docker/skopeo pulls work behind a TLS-intercepting proxy.
    mkdir -p "${SDK_OUT}/certs"
    cat > "${SDK_OUT}/certs/README" <<'CERTEOF'
vcontainer CA certificate drop dir
==================================

Behind a corporate TLS-intercepting proxy (e.g. Zscaler), the container VM
(vdkr/vpdmn) or the Xen dom0 (vxn) does not trust the proxy's root CA, so image
pulls from docker.io fail with:

    x509: certificate signed by unknown authority

FIX: copy your corporate root CA certificate(s) into THIS directory:

    certs/your-corporate-root-ca.crt        (PEM format: .crt / .pem / .cer)

Then re-run any vdkr / vpdmn / vxn command. The certificate(s) are transported
into the VM/dom0 over a read-only 9p share and installed into its system trust
store (update-ca-certificates) on every boot -- the same thing an OS admin does
on a native machine. For vxn, the CA is also propagated into each container
(DomU) so containers that make their own TLS calls trust it too.

Getting the cert (AMD/Zscaler example): it is usually already in the host trust
store, e.g.
    cp /usr/local/share/ca-certificates/amd-corporate-root-ca.crt certs/

Override the location with VCONTAINER_CA_DIR=/path/to/certs if you prefer.
CERTEOF
    bbnote "Created certs/ drop-dir + README"

    # Create README
    cat > "${SDK_OUT}/README.txt" <<EOF
vcontainer Standalone SDK
=========================

This is a self-contained, relocatable distribution of vdkr (Docker) and
vpdmn (Podman) CLI tools for cross-architecture container operations.

Quick Start:
  source init-env.sh
  vdkr-x86_64 images      # Docker for x86_64
  vpdmn-aarch64 images    # Podman for aarch64

Architectures included: ${ARCHITECTURES}

Contents:
  init-env.sh               - Environment setup script (interactive bash)
  environment-setup-ci      - CI environment (for yocto-autobuilder-helper)
  vdkr, vdkr-<arch>        - Docker CLI wrapper
  vpdmn, vpdmn-<arch>   - Podman CLI wrapper
  vrunner.sh            - Shared QEMU runner
  vcontainer-common.sh  - Shared CLI code
  vdkr-blobs/           - Docker QEMU blobs (per-arch subdirectories)
  vpdmn-blobs/          - Podman QEMU blobs (per-arch subdirectories)
  sysroots/             - SDK binaries (QEMU, socat, libraries)
  registry/ca.crt       - CA cert for secure registry (if CONTAINER_REGISTRY_SECURE=1)

Secure Registry Usage:
  vdkr --secure-registry --ca-cert registry/ca.crt pull myimage

Requirements:
  - Linux x86_64 host
  - KVM support recommended (for performance)

Corporate TLS proxy (e.g. Zscaler):
  If image pulls fail with "x509: certificate signed by unknown authority",
  drop your corporate root CA (PEM/.crt) into certs/ and re-run. It is installed
  into the VM/dom0 trust store on boot. See certs/README.

For more information:
  https://git.yoctoproject.org/meta-virtualization/
EOF

    # vxn (opt-in) works differently from vdkr/vpdmn -- document it only when included
    if [ -f "${SDK_OUT}/vxn" ]; then
        cat >> "${SDK_OUT}/README.txt" <<EOF

vxn (Docker for Xen)
====================
vxn runs containers as Xen PV DomU guests. A Xen dom0 image is bundled and run
under QEMU (KVM-accelerated); works on a Linux host or WSL2 with /dev/kvm. Two
ways to use it:

  Mode 1 -- transparent host CLI (the vdkr/vpdmn UX):
    vxn-x86_64 run --rm alpine echo hi
  The dom0 boots once under QEMU and stays resident (memres); later commands
  reuse it. vxn auto-selects the qemu-xen backend from the bundled dom0 .wic.

  Mode 2 -- docker/podman UI (drive dom0's engine from the host):
    vxn-x86_64 vmemres start
    eval "\$(vxn-x86_64 vexpose env --export)"   # sets DOCKER_HOST + API version
    docker run --network=none --rm alpine echo hi
  Uses your host's docker/podman CLI against dom0's engine (which creates a
  DomU via vxn-oci-runtime). Requires the vxn-podman-api package in the dom0
  image. --network=none is required; the DomU still gets its own networking.
  Run 'vxn-x86_64 vexpose' (no args) for the full explanation.

  Mode 3 -- interactive dom0 shell:
    ./boot-xen.sh                        # boot Xen dom0 (KVM); Ctrl-A X to quit
    (in dom0) vxn run --rm alpine echo hi
    ssh -p 18022 root@localhost           # reach the booted dom0

Tunables (env vars): VXN_VCPUS, VXN_MEM, VXN_SSH_PORT, VXN_API_PORT, VXN_IMAGE.
Contents: vxn, vxn-<arch>, vrunner-backend-qemu-xen.sh, boot-xen.sh,
          vxn-blobs/ (per-arch Xen dom0 image)
EOF
        bbnote "Documented vxn in README"
    fi

    bbnote "vcontainer blobs and scripts added to SDK"

    # -----------------------------------------------------------------------
    # Step 2: Create environment script (after blobs so we can check for them)
    # -----------------------------------------------------------------------

    # Remove ALL default SDK files - we create our own
    rm -f ${SDK_OUTPUT}/${SDKPATH}/site-config-*
    rm -f ${SDK_OUTPUT}/${SDKPATH}/version-*
    rm -f ${SDK_OUTPUT}/${SDKPATH}/environment-setup-*

    # Create vcontainer-specific environment script
    # Keep the environment-setup-* naming so SDK installer works
    script=${SDK_OUTPUT}/${SDKPATH}/environment-setup-${REAL_MULTIMACH_TARGET_SYS}

    # Create environment script
    # Set OECORE_NATIVE_SYSROOT temporarily for SDK relocation, then unset it
    # (like buildtools-tarball does to avoid confusing other Yocto tools)
    cat > $script <<'HEADER'
#!/bin/bash
# vcontainer environment setup script
# Source this file: source environment-setup-none
# Or use the symlink: source init-env.sh

VCONTAINER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HEADER
    # Yocto variables (${SDK_SYS}, ${SDKPATHNATIVE}) expand at parse time
    # Shell variables use $VAR to avoid Yocto expansion
    echo 'export OECORE_NATIVE_SYSROOT="'"${SDKPATHNATIVE}"'"' >> $script
    echo 'export PATH="$VCONTAINER_DIR:$OECORE_NATIVE_SYSROOT/usr/bin:/usr/bin:/bin:$PATH"' >> $script
    cat >> $script <<'FOOTER'

echo "vcontainer environment configured."
echo ""
FOOTER

    # Add usage info based on what's included (check files we just copied)
    if [ -f "${SDK_OUT}/vdkr" ]; then
        cat >> $script <<'ENVEOF'
echo "vdkr (Docker) commands:"
echo "  vdkr images              # List docker images"
echo "  vdkr vimport ./oci/ app  # Import OCI directory"
ENVEOF
    fi

    if [ -f "${SDK_OUT}/vpdmn" ]; then
        cat >> $script <<'ENVEOF'
echo "vpdmn (Podman) commands:"
echo "  vpdmn images             # List podman images"
echo "  vpdmn vimport ./oci/ app # Import OCI directory"
ENVEOF
    fi

    if [ -f "${SDK_OUT}/vxn" ]; then
        cat >> $script <<'ENVEOF'
echo "vxn (Docker for Xen) -- containers as Xen DomU guests:"
echo "  vxn-x86_64 run --rm alpine echo hi   # transparent: boots dom0 under QEMU"
echo "  vxn-x86_64 vmemres start; eval \"\$(vxn-x86_64 vexpose env --export)\""
echo "    then: docker run --network=none --rm alpine echo hi   # docker/podman UI"
echo "  ./boot-xen.sh                        # or interactive dom0 shell (Ctrl-A X quits)"
echo "  vxn-x86_64 vexpose                   # explains the docker/podman UI"
ENVEOF
    fi

    cat >> $script <<ENVEOF
echo ""
echo "Behind a TLS proxy (x509 pull errors)? drop your corporate root CA into"
echo "  \$VCONTAINER_DIR/certs/   (see certs/README)"
echo ""
echo "Architectures: ${VCONTAINER_ARCHITECTURES}"
ENVEOF

    # Unset OECORE_NATIVE_SYSROOT to avoid confusing other Yocto tools
    # (same pattern as buildtools-tarball)
    echo '' >> $script
    echo '# Clean up - unset to avoid confusing other Yocto tools' >> $script
    echo 'unset OECORE_NATIVE_SYSROOT' >> $script

    # Replace placeholder with actual SDK_SYS
    sed -i -e "s:@SDK_SYS@:${SDK_SYS}:g" $script
    chmod 755 $script

    # Create init-env.sh symlink for convenience
    ln -sf environment-setup-${REAL_MULTIMACH_TARGET_SYS} ${SDK_OUTPUT}/${SDKPATH}/init-env.sh

    # -----------------------------------------------------------------------
    # CI/AutoBuilder environment script
    # -----------------------------------------------------------------------
    # yocto-autobuilder-helper's enable_tools_tarball() parses environment
    # scripts line-by-line in Python.  It only honours lines starting with
    # "export " at column 0, only substitutes $PATH, and treats "unset " at
    # column 0 as a removal.  It does NOT evaluate shell expressions like
    # $(...) or variable references like $FOO.
    #
    # Rather than adding conditional logic to the interactive bash script,
    # generate a separate flat file with baked-in absolute paths that the
    # AB parser can consume directly.  SDK relocation rewrites these paths
    # at install time just like the primary environment-setup-* script.
    ci_script=${SDK_OUTPUT}/${SDKPATH}/environment-setup-ci
    cat > $ci_script <<CISCRIPT
# vcontainer CI environment — for yocto-autobuilder-helper
# Flat export lines with absolute paths; no shell logic.
# SDK relocation rewrites these paths at install time.
export VCONTAINER_DIR="${SDKPATH}"
export OECORE_NATIVE_SYSROOT="${SDKPATHNATIVE}"
export PATH="${SDKPATH}:${SDKPATHNATIVE}/usr/bin:\$PATH"
# Clean up - unset to avoid confusing other Yocto tools'
unset OECORE_NATIVE_SYSROOT
CISCRIPT
    chmod 755 $ci_script

    # Create version file
    echo "vcontainer SDK version: ${PV}" > ${SDK_OUTPUT}/${SDKPATH}/version.txt
    echo "Built: $(date)" >> ${SDK_OUTPUT}/${SDKPATH}/version.txt
    echo "Architectures: ${VCONTAINER_ARCHITECTURES}" >> ${SDK_OUTPUT}/${SDKPATH}/version.txt

    # -----------------------------------------------------------------------
    # Step 3: Remove unnecessary files to reduce SDK size (~100MB savings)
    # -----------------------------------------------------------------------
    bbnote "Removing unnecessary files from SDK..."

    # Remove locale data (~97MB) - not needed for vcontainer tools
    rm -rf ${SDK_OUTPUT}/${SDKPATHNATIVE}/usr/lib/locale
    bbnote "Removed locale data"

    # Remove QEMU user-mode emulators (we only need system emulators)
    # Keep: qemu-system-aarch64, qemu-system-x86_64
    for qemu_bin in ${SDK_OUTPUT}/${SDKPATHNATIVE}/usr/bin/qemu-*; do
        case "$(basename $qemu_bin)" in
            qemu-system-aarch64|qemu-system-x86_64|qemu-img|qemu-nbd)
                # Keep these
                ;;
            qemu-system-*)
                # Remove other system emulators (handled by QEMU_TARGETS now, but just in case)
                rm -f "$qemu_bin"
                ;;
            *)
                # Remove user-mode emulators (qemu-aarch64, qemu-arm, etc.)
                rm -f "$qemu_bin"
                bbnote "Removed $(basename $qemu_bin)"
                ;;
        esac
    done

    bbnote "SDK size optimization complete"
}

create_sdk_files[vardeps] += "VCONTAINER_TARGET_ARCH VCONTAINER_KERNEL_NAME VCONTAINER_MC VCONTAINER_INCLUDE_VXN"

# ===========================================================================
# Substitute custom placeholders in installer script
# ===========================================================================
# This runs AFTER archive_sdk to replace placeholders in our custom template
SDK_POSTPROCESS_COMMAND += "substitute_vcontainer_vars;"

substitute_vcontainer_vars () {
    # Replace placeholders in the installer script
    # Use SDKDEPLOYDIR (work directory) not SDK_DEPLOY (final deploy location)
    sed -i -e "s|@VCONTAINER_ARCHITECTURES@|${VCONTAINER_ARCHITECTURES}|g" ${SDKDEPLOYDIR}/${TOOLCHAIN_OUTPUTNAME}.sh
    bbnote "Substituted VCONTAINER_ARCHITECTURES=${VCONTAINER_ARCHITECTURES} in installer"
}

substitute_vcontainer_vars[vardeps] += "VCONTAINER_ARCHITECTURES"

# ===========================================================================
# Print usage information after SDK is built
# ===========================================================================
python do_populate_sdk:append() {
    import os

    deploy_dir = d.getVar('SDK_DEPLOY')
    toolchain_outputname = d.getVar('TOOLCHAIN_OUTPUTNAME')
    architectures = d.getVar('VCONTAINER_ARCHITECTURES').split()

    # Find the installer script. Report its final SDK_DEPLOY path (where the
    # user will find it), but size it from the SDKDEPLOYDIR work copy: this runs
    # in do_populate_sdk:append, before the .sh is copied out to SDK_DEPLOY, so
    # getsize() on the final path reads 0 (the "Size: 0 MB" banner bug).
    installer = os.path.join(deploy_dir, toolchain_outputname + '.sh')
    installer_workdir = os.path.join(d.getVar('SDKDEPLOYDIR'),
                                     toolchain_outputname + '.sh')
    installer_size = 0
    if os.path.exists(installer_workdir):
        installer_size = os.path.getsize(installer_workdir) // (1024 * 1024)
    elif os.path.exists(installer):
        installer_size = os.path.getsize(installer) // (1024 * 1024)

    # Check what was included
    sdk_output = d.getVar('SDK_OUTPUT')
    sdkpath = d.getVar('SDKPATH')
    sdk_out = os.path.join(sdk_output, sdkpath.lstrip('/'))
    vdkr_included = os.path.exists(os.path.join(sdk_out, 'vdkr'))
    vpdmn_included = os.path.exists(os.path.join(sdk_out, 'vpdmn'))
    vxn_included = os.path.exists(os.path.join(sdk_out, 'boot-xen.sh'))

    bb.plain("")
    bb.plain("=" * 70)
    bb.plain("vcontainer SDK tarball created:")
    bb.plain("  %s" % installer)
    bb.plain("  Size: %d MB" % installer_size)
    bb.plain("  Architectures: %s" % " ".join(architectures))
    bb.plain("  vdkr (Docker): %s" % ("included" if vdkr_included else "NOT included"))
    bb.plain("  vpdmn (Podman): %s" % ("included" if vpdmn_included else "NOT included"))
    bb.plain("  vxn (Docker/Xen): %s" % ("included" if vxn_included else "NOT included"))
    bb.plain("")
    bb.plain("To extract and use:")
    bb.plain("  %s -d /tmp/vcontainer -y" % installer)
    bb.plain("  cd /tmp/vcontainer")
    bb.plain("  source init-env.sh")
    for arch in architectures:
        if vdkr_included:
            bb.plain("  vdkr-%s images      # Docker for %s" % (arch, arch))
        if vpdmn_included:
            bb.plain("  vpdmn-%s images     # Podman for %s" % (arch, arch))
    if vxn_included:
        bb.plain("  ./boot-xen.sh        # boot Xen dom0, then run vxn inside it")
    bb.plain("=" * 70)
}
